server:
  port: 8099    #default port where the service will be started
 
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:    
  application:
    name: user-service   #current service name to be used by the eureka server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        userSubscriptionsChannel:
          destination: userSubscriptions
      default:
        contentType: application/json

management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
 
 
logging:
  level:
    pericles: DEBUG